#!/usr/bin/with-contenv sh

exec s6-setuidgid postgres stolon-keeper --id postgres1 --port 15431 --pg-port 25431 --data-dir /var/lib/postgresql/data1 --pg-su-password=123456 --pg-repl-username=repl --pg-repl-password=123456 --cluster-name stolon-cluster --store-backend=consul --store-endpoints=consul:8500;
